filter:
    excluded_paths:
        - Tests/*
        - Formatter/DebugFormatter.php
build:
    nodes:
        analysis:
            tests:
                override:
                    - command: './vendor/bin/phpunit --coverage-clover=tests.coverage'
                      coverage:
                          file: 'tests.coverage'
                          format: 'php-clover'
                    - php-scrutinizer-run
    environment:
        php: 7.1
