filter:
    excluded_paths:
        - Tests/*
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=tests.coverage'
                coverage:
                    file: 'tests.coverage'
                    format: 'php-clover'