language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls: http://keylighter.kadet.net/_webhook/travis
