language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls: http://keylighter.kadet.net/travis-hook
