language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4
    - php: nightly

install:
  - composer install

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls: http://keylighter.kadet.net/_webhook/travis
