<?php return [
    'string'      => ['color' => 'green'],
    'keyword'     => ['color' => 'yellow'],
    'operator'    => ['color' => 'yellow'],
    'annotation'  => ['color' => 'magenta'],
    'symbol'      => ['bold'  => true],
    'variable'    => ['color' => 'blue'],
    'number'      => ['color' => 'light magenta'],
    'constant'    => ['color' => 'magenta'],
    'comment'     => ['color' => 'dark gray'],
    'tag'         => ['color' => 'yellow'],
    'delimiter'   => ['color' => 'light yellow', 'bold' => true],
    'call'        => ['color' => 'cyan'],
    'parameter'   => ['color' => 'dark gray'],

    'comment.docblock'     => ['color' => 'dark gray'],
    'variable.property'    => ['color' => 'light blue'],
    'variable.namespace'   => ['color' => 'light blue'],
    'symbol.attribute'     => ['color' => 'light magenta'],
    'symbol.tag'           => ['color' => 'yellow'],
    'annotation.arguments' => ['color' => 'default'],
    'variable.special'     => ['color' => 'magenta'],
    'variable.splat'       => ['color' => 'light blue'],

    'symbol.attribute.namespace'  => ['color' => 'magenta', 'bold' => true],
    'symbol.tag.namespace'        => ['color' => 'light yellow', 'bold' => true],
];