<?php return [
    'string'       => ['color' => 'green'],
    'keyword'      => ['color' => 'yellow'],
    'operator'     => ['color' => 'yellow'],
    'annotation'   => ['color' => 'magenta'],
    'symbol'       => ['color' => 'magenta'],
    'variable'     => ['color' => 'blue'],
    'number'       => ['color' => 'light magenta'],
    'constant'     => ['color' => 'magenta'],
    'comment'      => ['color' => 'dark gray'],
    'tag'          => ['color' => 'yellow'],
    'delimiter'    => ['color' => 'light yellow', 'bold' => true],
    'call'         => ['color' => 'cyan'],
    'parameter'    => ['color' => 'dark gray'],
    'preprocessor' => ['color' => 'dark gray'],
    'language'     => ['color' => 'default'],

    'symbol.class' => ['bold'  => true],
    'symbol.type'  => ['color'  => 'light red'],

    'constant.color' => ['color' => 'light yellow'],

    'comment.docblock'     => ['color' => 'dark gray'],
    'variable.property'    => ['color' => 'light blue'],
    'variable.namespace'   => ['color' => 'light blue'],
    'symbol.attribute'     => ['color' => 'light magenta'],
    'symbol.tag'           => ['color' => 'yellow'],
    'annotation.arguments' => ['color' => 'default'],
    'variable.special'     => ['color' => 'magenta'],
    'variable.scope'       => ['color' => 'light blue'],
    'variable.splat'       => ['color' => 'light blue'],

    'symbol.selector.class'        => ['color' => 'light red'],
    'symbol.selector.id'           => ['color' => 'red'],
    'symbol.selector.tag'          => ['color' => 'yellow'],
    'symbol.selector.class.pseudo' => ['color' => 'light red'],

    'symbol.attribute.namespace'  => ['color' => 'magenta', 'bold' => true],
    'symbol.tag.namespace'        => ['color' => 'light yellow', 'bold' => true],
];
